### ISSUE TITLE
LePage (QuTranscript Page: …) JSON parser error

### ISSUE THREAD

**Issue by RalfBarkow** [seandenigris/Quote-Me#14] opened 2022-02-22 07:17 UTC
[9twqvvxef6nlibyh4mv25ba3z.bak.zip](https://github.com/seandenigris/Quote-Me/files/8114265/9twqvvxef6nlibyh4mv25ba3z.bak.zip)

In my experiments with `QuTranscript`, I encountered a situation where the attached Lepiter page (.bak) showed as corrupted, and I received a Lepiter: Unable to load: Notification:
<img width="450" alt="Bildschirmfoto 2022-02-22 um 03 36 53" src="https://user-images.githubusercontent.com/1205477/155079894-9ff4ed44-1fd0-41a0-b19a-26557d869d5a.png">

due to a JSON parser error.

In the LePage (QuTranscript Page) context, I clicked on  `Copy a Remote Reference to the clipboard`: 
![Bildschirmfoto 2022-02-22 um 08 11 19](https://user-images.githubusercontent.com/1205477/155080861-d34c6be9-e2b2-4e6d-b3c9-20aab9a0e237.png)

Then in a new empty Note, paste this remote reference into a text snippet. Instead of referencing the existing QuTranscript Page, a new Named Page is created:
![Bildschirmfoto 2022-02-22 um 08 13 38](https://user-images.githubusercontent.com/1205477/155081176-ae687f52-616d-4ce9-847f-1d896e8bd633.png)
![Bildschirmfoto 2022-02-22 um 08 14 33](https://user-images.githubusercontent.com/1205477/155081651-f84afcfc-80bd-4eef-8022-244f46210723.png)

I would have expected the `QuTranscript Page` to be displayed instead.

**Comment by RalfBarkow** [comment] 2022-02-22 07:19
@seandenigris By the way: How can I delete the Lepiter page of a Transcript?

**Comment by RalfBarkow** [comment] 2022-02-22 11:32
I'm working on 2 computers: r and b. 
~/Dynabook and ~/Documents/lepiter/default are synced by Syncthing.
Dynabook on computer b is fine.
Starting it on computer b gives me a ```NotFound: [ :e | e uuid = uid ] not found in Array``` and all the Transcript lines are gone: (and no associated Lepiter page anymore)
<img width="1435" alt="Bildschirmfoto 2022-02-22 um 12 31 14" src="https://user-images.githubusercontent.com/1205477/155123757-0c87aa20-b737-4709-a23a-aed08b08c6a3.png">

**Comment by RalfBarkow** [comment] 2022-02-22 11:39
Maybe https://github.com/seandenigris/Quote-Me/blob/cfd36a40486a9157bdf4feaa564e9dbe17470d2d/src/QuoteMe-GToolkit/QuLeTranscriptLineSnippet.class.st is the relevant part of your code.

**Comment by RalfBarkow** [comment] 2022-02-22 16:09
> 1. JSON parse error
>        What is the result of the following for you? It parses okay for me (but the element doesn't display properly because the transcript doesn't exist in my model):
> 
> 
> ```smalltalk
> LeJsonV4 new deserialize: '9twqvvxef6nlibyh4mv25ba3z.bak' asFileReference contents readStream
> ```
![Bildschirmfoto 2022-02-22 um 17 04 49](https://user-images.githubusercontent.com/1205477/155171715-c3eca0a4-6550-4fef-bf28-ed5a4b3b16b3.png)

The result looks good: The LePage QuTranscript is displayed correctly.

**Comment by seandenigris** [comment] 2022-02-22 16:53
Was there a file with the same base but a `.corrupt` or other extension?

**Comment by RalfBarkow** [comment] 2022-02-22 18:20
@seandenigris  Yes, I moved the `.corrupt` files into a subdirectory, and reinstalled Dynabook in gt DEV v0.8.1235, then, e.g. ```cp corrupt/9twqvvxef6nlibyh4mv25ba3z.corrupt ./9twqvvxef6nlibyh4mv25ba3z.lepiter``` copied the missing transcript back. I think the problem was issue "4. Missing subject …" ('Transcript subject not found'). 

Now everything is good again on my side. Thank you!

**Comment by seandenigris** [comment] 2022-02-22 19:07
Okay, great. Let’s leave this open so I remember to look into no. 2 and 3

**Comment by RalfBarkow** [comment] 2022-02-22 20:41
@seandenigris Perhaps I was a bit hasty in giving the all-clear about the 'Transcript subject not found' warnings:
<img width="1312" alt="Bildschirmfoto 2022-02-22 um 21 38 01" src="https://user-images.githubusercontent.com/1205477/155215207-f85637b8-f50f-4ccb-9aa9-8f3b5edae6ad.png">
I will continue to try to clean up my Lepiter default DB ...

**Comment by RalfBarkow** [comment] 2022-02-22 20:45
I got the .lepiter file with the "Dynamic Medium" text out of the way and the warning disappeared.

**Comment by seandenigris** [comment] 2022-02-22 22:24
What were you doing when you got the last 'Transcript subject not found' warning? Did the subject model in fact exist?

**Comment by RalfBarkow** [comment] 2022-02-22 23:00
@seandenigris I think I got some things mixed up and have yet to understand how exactly the Living Library/SP Data Backup and Restore, the Lepiter pages/databases, and the models are connected and interact. 

It is also not clear to me how to update a gt/Dynabook installation when a new gt build has been released. A vanilla gt installation does not yet know the custom leptier types, such as the transcript, so there are .corrupt files and 'Transcript subject not found' warnings. How do you update your gt/Dynabook version(s)?

**Comment by RalfBarkow** [comment] 2022-02-22 23:31
@seandenigris The JSON parser error reported at the beginning of this issue always occurs when using 
```curl https://dl.feenk.com/scripts/mac.sh | bash```
to build a new gt version if the default lepiter db already contains Transcript snippets. Starting that fresh gt version (without Dynabook installed) results in .corrupt file, which I have to rename to .lepiter once Dynabook is installed.

**Comment by seandenigris** [comment] 2022-02-23 02:24
> build a new gt version if the default lepiter db already contains Transcript snippets. Starting that fresh gt version (without Dynabook installed) results in .corrupt file(s), which I have to rename to .lepiter once Dynabook is installed.

Aha! Now we might be getting somewhere. I have separate playground and primary DBs. 

I also have two stages of loading:
1. My `~/Documents/lepiter/logical-database.properties` only loads my playground DB, which has no custom page types.
2. In my load script, *after* loading the Dynabook project, I first restore the spData and then load my primary DB, which contains the custom pages.

I forgot not everyone splits their playground and primary DBs. I'm not sure if custom page types can be loaded if this is not the case because of the issues you're encountering. The problem is that the custom page mechanism is a hack because Lepiter doesn't officially support that, so it is likely to cause chaos if the hack(s) are not installed first!

**Comment by seandenigris** [comment] 2022-02-23 02:28
> how exactly the Living Library/SP Data Backup and Restore, the Lepiter pages/databases, and the models are connected and interact.

The main challenge is that either the model or Lepiter can change out from under the other side without warning, so we don't store any object pointers on either side, only UIDs.
- Living library
  - like other Dynabook components, has the capability to generate UIDs for certain objects
  - Transcripts store the UID of their corresponding Lepiter page
- SP Data stores all Dynabook object, including all living library ones
- The Lepiter pages referencing Dynabook objects do so via reference objects that store the object's UID as well as information about which singleton to look for the object in (e.g. MpAddressBook uniqueInstance, PpEventLog uniqueInstance).

Let me know if that clears anything up...

**Comment by RalfBarkow** [comment] 2022-02-23 05:31
@seandenigris Thank you Sean for your detailed explanations, which indeed made a lot of things clearer for me.

What do you think about storing the transscripts in a separate lepiter db (not in the lepiter default db)?
<img width="1392" alt="Bildschirmfoto 2022-02-23 um 06 23 19" src="https://user-images.githubusercontent.com/1205477/155266323-0b009ed4-a0a9-4d27-b941-a17cfe70e693.png">

**Comment by seandenigris** [comment] 2022-02-23 06:58
> What do you think about storing the transscripts in a separate lepiter db (not in the lepiter default db)?

I'm guessing maybe it should be configurable. For myself, I like having them in the primary DB because I want to be able to refer to them easily (autocomplete, etc) from any of my other pages.

**Comment by seandenigris** [comment] 2022-03-03 15:16
I created [a new repo](https://github.com/seandenigris/Objective-Lepiter) for Lepiter-pages-for-arbitrary-objects code because I'm getting confused by issues distributed among several repos and also the code is generally useful. I think I captured all the open loops from this issue in issues in the news repo, so I'll close this.

**Closed by seandenigris** 2022-03-03 15:16 UTC
